### ISSUE TITLE
项目中使用compileSdk 30情况下集成该项目冲突

### ISSUE THREAD

**Issue by white1208** [SDBridge/SDBridgeJava#1]
我项目中使用的compileSdk是30，但是咱们项目中使用的是31，如果我这边升级成31，就得集成java11，能在不升级的情况下，集成咱们项目么

**Comment by housenkui** [comment]
<img width="786" alt="image" src="https://user-images.githubusercontent.com/5885635/175807540-0a0b82b6-dd32-49ec-974a-8664a9dae4b2.png">

直接把文件拖到项目里面试一试.

**Comment by housenkui** [comment]
@white1208
